### ISSUE TITLE
tools makefile

### ISSUE THREAD

**Issue by user-8472** [cyrozap/libcyusbserial#1]
In the tools Makefile line 11:
-   $(CC) $(CFLAGS) $(LDFLAGS) -o $@ $< 
-   $(CC) $(CFLAGS) -o $@ $< $(LDFLAGS)

**Comment by cyrozap** [comment]
I'm not sure what the issue is. Do you want me to change that line to what you've written? If so, why? What issue(s) are you experiencing?

**Comment by user-8472** [comment]
Maybe my version of the compiler acts differently but the build fails for
me with the arguments in the order you had originally listed. Libraries to
link against have to come earlier in the argument list.

Chris

**Comment by cyrozap** [comment]
Ah, I see. I had only tested the build on OS X when I was working on that file, so it must be a clang/gcc difference. I'll test it on one of my Linux machines when I get the chance. Once I see it can build on both, I'll commit the change.

**Comment by cyrozap** [comment]
Sorry for the delay, but I just tried building it today and it worked fine using both gcc 4.9.2 and clang 3.5.1. What compiler are you using?

**Comment by user-8472** [comment]
Looks like this has been a waste of time.  I apologize. I went back to
compile again with the original branch on my system (Ubuntu 14, gcc 4.8.2)
and everything was fine with that command.  I must have gotten lost the
code while putting together patches. JTAG debugging now works on Linux for
the Cypress FX3! It doesn't look like there was anything wrong with your
repository.

Thanks again for putting it up. It was more convenient than what was being
supplied directly from Cypress' website.

Chris

**Comment by cyrozap** [comment]
I'm glad you were able to make use of this library! Being "more convenient" than the official one was exactly what I intended.

**Comment by cyrozap** [comment]
I just pushed some commits that _should_ fix the build when using gcc. Until recently, I was unaware that the order of library arguments is important to gcc.
